const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Behaviors.Timer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Cnds.OnFall,
		C3.Behaviors.Platform.Acts.FallThrough,
		C3.Plugins.Sprite.Cnds.OnURLLoaded,
		C3.Plugins.Sprite.Cnds.HasChildren
	];
};
self.C3_JsPropNameTable = [
	{Plataforma: 0},
	{DesplazarHasta: 0},
	{Jugador: 0},
	{Sólido: 0},
	{FondoEnMosaico: 0},
	{Seno: 0},
	{Tomate: 0},
	{Teclado: 0},
	{Sprite: 0},
	{Jugador2: 0},
	{FondoEnMosaico2: 0},
	{Texto: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Parpadeo: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Temporizador: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0}
];

self.InstanceType = {
	Jugador: class extends self.ISpriteInstance {},
	FondoEnMosaico: class extends self.ITiledBackgroundInstance {},
	Tomate: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Jugador2: class extends self.ISpriteInstance {},
	FondoEnMosaico2: class extends self.ITiledBackgroundInstance {},
	Texto: class extends self.ITextInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {}
}